### ISSUE TITLE
Support the `files` property in `package.json`

### ISSUE THREAD

**Issue by lorensr** [microsoft/vscode-vsce#867] opened 2023-05-18 07:16 UTC
Currently, `vsce ls` ignores my `files` allowlist, which means the only way to configure which files are published is with the `.vscodeignore` denylist. Allowlists are safer and more maintainable than denylists, and `files` is the standard in the ecosystem. #12 is an older version of this feature request, and includes 15 upvotes for the workaround, which no longer works.

**Comment by joaomoreno** [comment] 2023-06-12 14:19
I would consider supporting this behind a flag, ie `vsce publish --use-files-prop`.

**Comment by JacksonTian** [comment] 2023-11-10 06:26
The `.vscodeignore` is blocklist, the `files` is allowlist.

**Comment by wasmftw** [comment] 2024-01-05 20:56
I'd like to take this up @joaomoreno.

A minimal fix for this could be adding a `allowlist` parameter to the `collectAllFiles` function at 

https://github.com/microsoft/vscode-vsce/blob/6e959ca5219c282f10e6d90b9dfd53ba4263b01b/src/package.ts#L1567

i.e. if there exists a `files` property in the manifest then we filter out the output of the `collectAllFiles` function to only contain files from the allowlist. Would appreciate the guidance of the community on this.

**Closed** 2024-04-10 13:50 UTC
Labels: help wanted, feature-request

**Comment by vanyauhalin** [comment] 2024-04-10 14:03
@benibenj, thank you! Could you please let us know when we might be able to start using this?

**Comment by benibenj** [comment] 2024-04-12 10:26
@vanyauhalin We just released a new version which includes the change

**Comment by benibenj** [comment] 2024-04-22 09:50
@vanyauhalin Have you adopted the `files` property already? If so, can you confirm it works as intended?

**Comment by vanyauhalin** [comment] 2024-05-01 10:24
@benibenj Apologize for the delayed response. Works [perfectly](https://github.com/vanyauhalin/moondusttheme/commit/afd464643790a05fe89b2f4aa5300835427707b1/). Thank you.
