### ISSUE TITLE
vsce ls fails with yarn v2 config files

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode-vsce#750] opened 2022-06-27 12:50 UTC
```
$ npx vsce ls
 INFO  Detected presence of yarn.lock. Using 'yarn' instead of 'npm' (to override this pass '--no-yarn' on the command line).
 ERROR  Command failed: yarn list --prod --json
```

There is no `list` in yarn 2 and if you try to pass `--no-yarn` to vsce, you endup with the other problems and failures.

As a temporary workaround I could replace replace `vsce ls` with `zipinfo -1 *.vsix` to perform the listing but that would not work if other tools/libraries are calling `vsce ls` themselves. It is still broken.

Related: #517

**Comment by joaomoreno** [comment] 2022-06-27 12:52
Duplicate of https://github.com/microsoft/vscode-vsce/issues/517

**Comment by ssbarnea** [comment] 2022-06-27 12:53
Sorry, I seen original OP closing it. In fact is not a full duplicate, that one is specific, we might have other broken things related to general compatibility with yarn v2.

**Closed by joaomoreno** 2022-06-27 12:52 UTC
