### ISSUE TITLE
Full parity on keywords with MP

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-vsce#93] opened 2016-05-31 18:42 UTC
MP folks are running an implementation of this pseudocode on the INT database. Once we confirm the data looks good we'll run it on prod. 

We will want to bring full parity with what happens on update for VSCE. The psuedocode is [here](https://github.com/Microsoft/vscode-marketplace/blob/master/tag-seeding-algorithm.js).

Couple things that have evolved since #83. 
- if we detect `contributes.keybindings` tag with `keybindings`
- if we detect `contributes.debuggers` tag with `debuggers`
- if we detect `contributes.jsonValidation` tag with `json`
- use alias to keword map (see [here](https://github.com/Microsoft/vscode-marketplace/blob/master/tag-seeding-algorithm.js#L7)) on description (see [here](https://github.com/Microsoft/vscode-marketplace/blob/master/tag-seeding-algorithm.js#L103))
- if we detect `contributes.grammars.language`, tag with `{ language }`
- if we detect `contributes.languages` then, tag with `{ language.id }`, ` { language.aliases }`, and create hidden keywords for `{ language.extensions }`. Hidden = `$ext_{ language.extensions }`. See [here](https://github.com/Microsoft/vscode-marketplace/blob/master/tag-seeding-algorithm.js#L66). 

My thought is let's wait until MP engineers run this on the INT environment before we make the changes.

**Comment by joaomoreno** [comment] 2016-06-01 09:40
Closing as duplicate of #94.

**Closed by joaomoreno** 2016-06-01 09:40 UTC
