### ISSUE TITLE
Invalid error on bad cmd; undefined(?) passed to Leven (TypeError: right.charCodeAt is not a function)

### ISSUE THREAD

**Issue by o4dev** [microsoft/vscode-vsce#516] opened 2020-12-15 23:52 UTC
When packaging _(with a bad cmd)_ on a fresh install this _invalid(?)_ error occurs:

```
bash-3.2$ vsce vscode-client/
/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/leven/index.js:26
	while (leftLength > 0 && (left.charCodeAt(~-leftLength) === right.charCodeAt(~-rightLength))) {
	                                                                  ^

TypeError: right.charCodeAt is not a function
    at leven (/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/leven/index.js:26:68)
    at /Users/luke/.npm-global/lib/node_modules/vsce/out/main.js:146:60
    at Array.find (<anonymous>)
    at /Users/luke/.npm-global/lib/node_modules/vsce/out/main.js:146:50
    at Command.outputHelp (/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/commander/index.js:1634:22)
    at Command.help (/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/commander/index.js:1676:10)
    at Command.<anonymous> (/Users/luke/.npm-global/lib/node_modules/vsce/out/main.js:144:17)
    at Command.listener [as _actionHandler] (/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/Users/luke/.npm-global/lib/node_modules/vsce/node_modules/commander/index.js:953:18)
```

Reproduce:
 - `Make a demo extension with yo code and add a publisher`
 - from parent directory run `vsce  [extention_dir_name]`

Expected:
 - `Error: Command '[extention_dir_name]' is invalid.`
 
Actual Result:
 - Command is processed and sent to library Leven which then tries to access a sting function that doesn't exist.
 - `TypeError: right.charCodeAt is not a function`

Platform:
 - MacOS `10.15.67`
 - vsce `1.81.1`
 - node `v12.16.3`
 - `npm@7.0.10`.

Initially I presumed it was an error with my code however looking at the stack trace it seems `main.js:146:60` uses `leven` which tries to call `left.charCodeAt`. Presumably `left` or `right` is undefined.

### EDIT: I now realise it was an incorrect command however this doesn't explain why instead of telling the user, it ties to process it though Leven (presumably to find similar?) but this isn't in the documentation. Furthermore surely, even if its trying to find a similar command, undefined shouldn't be passed. This whole post has been largely modified to reflect this issue better.

**Comment by o4dev** [comment] 2020-12-16 00:02
Apologies, this was my fault I was calling the program in the wrong way. Presumed 'package' was the actual name/directory of the package. The help description makes this very clear. **Although, I feel it should not have accepted the cmd at all.** It should _especially_ not try to **process** it. Well, there's **no** indication of this _functionality in the help description._

**Comment by o4dev** [comment] 2020-12-16 00:22
### I am reopening this post because although my issue has been solved, the behaviour is still unexpected and completely undefined in the documentation.

**Comment by joaomoreno** [comment] 2020-12-16 10:56
Duplicate of https://github.com/microsoft/vscode-vsce/issues/502

This was already fixed, you can just update to the latest vsce version.

**Closed by joaomoreno** 2020-12-16 10:56 UTC
