### ISSUE TITLE
Packaging an ext in an npm workspace with a dependency fails in a strange way

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-vsce#900] opened 2023-09-19 16:17 UTC
1. Create an npm workspace with an extension that has a dependency on another package in a workspace
2. Run `vsce package`
3. See the following error

![Image](https://github.com/microsoft/vscode-vsce/assets/2230985/6cf3bfce-5b94-404f-a187-f62a1b90b2de)

It seems like vsce discovers and tries to bundle _everything_ in the workspace rather than just the extension and its dependency. Packaging with `--no-dependencies` eliminates the error. We should handle this or fail in a better way

**Comment by joaomoreno** [comment] 2023-09-21 07:15
Duplicate of https://github.com/microsoft/vscode-vsce/issues/580

**Closed by joaomoreno** 2023-09-21 07:15 UTC
