### ISSUE TITLE
No way to prevent url replace in README

### ISSUE THREAD

**Issue by fangbinwei** [microsoft/vscode-vsce#453] opened 2020-05-31 12:34 UTC
When execute `vsce package`, `vsce`  will do url replace in README, so that some relative assets in github can be accessed correctly.

Coincidentally, my README contains something like below to explain the default value of the extension configuration. It seems there is no way to prevent url replace, maybe string in code block shouldn't be handled? It's better I delete it, right?
```
Default: `![${fileName}](${url})`
```

parsed to 
```
Default: ![${fileName}](https://github.com/fangbinwei/aliyun-oss-uploader/raw/master/${url})
```

**Comment by joaomoreno** [comment] 2021-11-02 15:43
Duplicate of #327

**Closed by joaomoreno** 2021-11-02 15:43 UTC
Labels: bug
