### ISSUE TITLE
vsce package : ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vscode-vsce#477] opened 2020-08-09 18:44 UTC
```log
> webpack --mode production

Hash: ________________
Version: webpack 4.44.1
Time: 7956ms
Built at: 08/09/2020 2:00:24 PM
           Asset      Size  Chunks                   Chunk Names
    extension.js   284 KiB       0  [emitted]        main
extension.js.map  1020 KiB       0  [emitted] [dev]  main
Entrypoint main = extension.js extension.js.map
 [77] external "util" 42 bytes {0} [built]
[125] external "fs" 42 bytes {0} [built]
[189] ./src/extension.ts 5.8 KiB {0} [built]
[190] external "vscode" 42 bytes {0} [built]
[408] external "stream" 42 bytes {0} [optional] [built]
[409] external "string_decoder" 42 bytes {0} [built]
[410] external "events" 42 bytes {0} [built]
[412] external "timers" 42 bytes {0} [built]
[457] external "path" 42 bytes {0} [built]
    + 449 hidden modules
 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
```

**Comment by pmahend1** [comment] 2020-08-09 18:45
Related to #432  #439

**Comment by meilZhu** [comment] 2020-08-28 15:47
Hello! At first, when I packaged the vscode plug-in, I reported an error as follows

Error: Command failed: npm list --production --parseable --depth=99999`
npm ERR! missing: lodash@, required by kissy-xtemplate@0.4.3

However, according to the feedback from GitHub, it was the NPM version problem. I said that NPM version 5.5.1 was needed. However, after the version was changed here, the following errors appeared again

report errors

ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! cb.apply is not a function

**Comment by joaomoreno** [comment] 2020-08-31 13:15
Dupe of https://github.com/microsoft/vscode-vsce/issues/439

**Closed by joaomoreno** 2020-08-31 13:15 UTC

**Comment by bs** [comment] 2020-09-26 04:46
For people who find this via search, a work-a-round is `vsce package --yarn` as described in #432.

**Comment by niccolomineo** [comment] 2022-07-19 12:31
I just had to do `npm upgrade`, first, and it worked.

**Comment by westqzy** [comment] 2023-11-23 02:11
> 我只需`npm upgrade`要先这样做，它就起作用了。

It works!
