### ISSUE TITLE
Add a changelog to the repository for features, user changes and bug fixes

### ISSUE THREAD

**Issue by zimmski** [microsoft/vscode-vsce#613] opened 2021-09-12 21:48 UTC
It looks like this repository is missing a changelog file (or even doing the changelog in the releases would be nice). This would help users of the "vsce" command to figure out if they need to adapt their extensions of configuration somehow.

One example for a change that is good to know is https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions which is available with vsce 1.99.0. However, i cannot really figure that out with the commit messages nor the issues. Grooming of the commit messages would help too i guess.

**Comment by zimmski** [comment] 2021-09-12 22:06
Another example: I just wanted to report that .vscodeignore does not allow to "allowlist" instead of "disallowlist" and wanted to create an example, well, now it works :ping_pong:

**Comment by joaomoreno** [comment] 2021-09-28 18:42
Dupe of https://github.com/microsoft/vscode-vsce/issues/541

**Closed by joaomoreno** 2021-09-28 18:42 UTC
