### ISSUE TITLE
Local publish command

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode-vsce#80] opened 2016-03-06 19:16 UTC
Kinda related to the link command (#78), though I'd like something slightly different: to be able copy an extension I'm currently working on into a vscode installation, but in its current state, rather than create a symlink, so I can tweak some more, switch branches etc. without affecting the installed version.

**Comment by SrTobi** [comment] 2016-03-06 21:27
You can pack the extension with [`vsce package`](https://code.visualstudio.com/docs/tools/vscecli#_packaging-extensions) and install this package using [`code myExtensionFolder\myExtension.vsix`](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix)

**Comment by stkb** [comment] 2016-03-06 22:16
Hmm thanks, I guess that is pretty simple. But I'll leave this here in case it can be made any simpler :)

A problem I have noticed though, is that if you install an extension with a .vsix in this way, and then try to install a newer version (though without bumping the version number) vscode will fail to install the extension (not with an error message; it will just fail).

**Comment by joaomoreno** [comment] 2016-03-07 09:45
I'll close this as duplicate of #78. If you want to have a copy of it and tweak it, just duplicate the extension's repository directory in disk and link that one. That would cover it right?

**Closed by joaomoreno** 2016-03-07 09:45 UTC
