### ISSUE TITLE
2.6.0 gives entrypoint missing error during packaging

### ISSUE THREAD

**Issue by bpringe** [microsoft/vscode-vsce#677] opened 2022-01-02 21:46 UTC
With the [Calva extension](https://github.com/BetterThanTomorrow/calva), version 2.6.0 of vsce causes the following error when running `npx vsce package --githubBranch published`:

```sh
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/extension
```

When I use vsce version 2.5.3, packaging completes successfully.

**Comment by bpringe** [comment] 2022-01-02 21:51
For more context, Calva's .vscodeignore blacklists everything and then whitelists files.

```
# Put everything on the blacklist by default
*
*/**
**/.DS_Store
*/**/.DS_Store

# Whitelist
!language-configuration.json
!clojure.tmLanguage.json
!assets/**
!out/**
!package.json
!README.md
!CHANGELOG.md
!LICENSE
!clojure-lsp.jar
!deps.clj.jar
!bundled/**
```

It seems like `!out/**` would cause `extension/out/extension` to be included, but maybe I'm missing something? I'm assuming the context of the .vscodeignore is within `extension/`. Is that correct?

**Comment by joaomoreno** [comment] 2022-01-03 09:51
Duplicate of https://github.com/microsoft/vscode-vsce/issues/675

**Closed by joaomoreno** 2022-01-03 09:51 UTC

**Comment by bpringe** [comment] 2022-01-04 03:36
I don't know how I didn't notice that. Thanks for informing me.
