### ISSUE TITLE
"yarn run vscode:prepublish"  resulting to vscode appears to be invalid error in release 1.81.0

### ISSUE THREAD

**Issue by tiwarishub** [microsoft/vscode-vsce#498] opened 2020-10-05 09:36 UTC
![image](https://user-images.githubusercontent.com/64764738/95063185-a80f0480-071b-11eb-8da0-5305103f1d76.png)
while running command `yarn run vscode:prepublish` for generating vsix file .

C:\vscode-deploy-azure>vsce package
Executing prepublish script 'yarn run vscode:prepublish'...                                                             
yarn run v1.22.5                                                                                                        
warning azure-deploy@1.2.0: The engine "vscode" appears to be invalid.                                                  
$ npm run compile

It has generated vsix , but that is an invalid vsix

When we downgraded to `1.80` it worked fine.

**Comment by felipecrs** [comment] 2020-10-05 10:22
This was probably fixed in 1.81.1.

**Comment by joaomoreno** [comment] 2020-10-05 13:17
This is something else.

@tiwarishub that isn't an error, but a warning. It's perfectly safe.

**Closed by joaomoreno** 2020-10-05 13:17 UTC

**Comment by tiwarishub** [comment] 2020-10-05 18:10
Hi @joaomoreno, but because of this warning the vsix file which was generated becomes an invalid one. I  will check with 1.81.1 , if this resolves the issue

**Comment by felipecrs** [comment] 2020-10-05 18:15
@tiwarishub your problem was not caused by this warning. It was caused by https://github.com/microsoft/vscode-vsce/issues/494.

**Comment by joaomoreno** [comment] 2020-10-06 08:19
>It has generated vsix , but that is an invalid vsix

Oh I see, I missed that! 👍 Thanks @felipecrs
