### ISSUE TITLE
`--yarn` can not work correctly after 1.81.0

### ISSUE THREAD

**Issue by YXL76** [microsoft/vscode-vsce#494] opened 2020-10-02 17:06 UTC
If project has `yarn.lock` file, `vsce` will use `yarn` automatically. However, when using `--yarn` flag, it will fall back to `npm`

**Comment by roydukkey** [comment] 2020-10-02 17:27
I don't use yarn and I received the following error:

```
% vsce package            
Executing prepublish script 'yarn run vscode:prepublish'...
/bin/sh: yarn: command not found
 ERROR  yarn failed with exit code 127
```

These are the only packages I have globally:

```
% npm -g list --depth 0
/usr/local/lib
├── n@6.7.0
├── npm@6.14.8
└── vsce@1.81.0
```

**Comment by marklawlor** [comment] 2020-10-03 00:10
In addition to @roydukkey comments. A fresh project with no `.yarnrc`, `yarn.lock` or `yarn` executable installed is defaulting to `yarn`.

**Comment by ranavale** [comment] 2020-10-03 02:24
- Azure build pipeline was working fine with vscode build plugin step (using `Executing prepublish script 'npm run vscode:prepublish'...`)
- I have not installed yarn neither my repo has anything related to yarn.
- Since today afternoon, prepublish is using `Executing prepublish script 'yarn run vscode:prepublish'...` and failing with 

```
'yarn' is not recognized as an internal or external command,
operable program or batch file.
 ERROR  yarn failed with exit code 1

```

**Comment by felipecrs** [comment] 2020-10-03 02:35
Does `--no-yarn` helps?

**Comment by ranavale** [comment] 2020-10-03 02:58
@felipecrs  It did not, as I am using azure build pipeline. rather I am not sure what changes/task I need to change in azure pipeline. My extension scripts are
```
    "scripts": {
        "vscode:prepublish": "npm run compile",
        "compile": "tsc -p ./",
        "watch": "tsc -watch -p ./",
        "test": "npm run compile && node ./node_modules/vscode/bin/test"
    },
```

**Comment by felipecrs** [comment] 2020-10-03 03:23
I can confirm the bug, I tried to debug but I was not able to.

For users facing this issue, I recommend to downgrade vsce:

```json
{
  "vsce": "1.80.0
}
```

**Comment by felipecrs** [comment] 2020-10-03 03:49
Okay, I found the issue.

The commander always set `yarn` to true, since `--no-yarn` is given as an option. I think it's not possible to define such an `undefined` option.

**Comment by felipecrs** [comment] 2020-10-03 04:10
Submitted a PR. This behavior was fixed in commander 3.0.0.

**Comment by ranavale** [comment] 2020-10-04 08:35
adding `--no-yarn` fixed the issue, but I think every user need to update their pipeline for this is not a good recommendation.

**Comment by felipecrs** [comment] 2020-10-04 17:01
> adding `--no-yarn` fixed the issue, but I think every user need to update their pipeline for this is not a good recommendation.

For sure, it's not a solution, just a workaround until the issue gets fixed.

However, I believe the best workaround so far is to downgrade the `vsce` to `1.80.0`.

**Comment by joaomoreno** [comment] 2020-10-05 09:33
Oof, sorry about that. Releasing a new version asap.

**Closed** 2020-10-05 09:42 UTC

**Comment by joaomoreno** [comment] 2020-10-05 09:43
Sorry for the breakage everyone. v1.81.1 is cooking right now with the fix and should be out in a few minutes.

**Comment by ranavale** [comment] 2020-10-05 16:23
Thank you very much. @felipecrs
