### ISSUE TITLE
Readme.md: links to other sections in same page are lost in generated html

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode-vsce#118] opened 2016-08-22 10:24 UTC
Given markdown:

``` markdown
[see below](#other-section)
```

Expected generated html (like on github)

``` html
<a href="#other-section">see below</a>
```

Actual generated html on the marketplace (hash part is lost)

``` html
<a href="">see below</a>
```

If the link is to another page however, then the hash part _is_ preserved

**Comment by joaomoreno** [comment] 2016-08-22 10:38
cc @pradeepna

**Comment by joaomoreno** [comment] 2016-08-22 10:39
Confirmed in https://marketplace.visualstudio.com/items?itemName=lukehoban.Go, just inspect the link for `Tools` in the `Using` section.

**Comment by joaomoreno** [comment] 2016-09-13 06:04
ping @modigrv @pradeepna

**Comment by vadimcn** [comment] 2016-10-07 02:00
Hi @joaomoreno, so what's the outlook on this one? 
Would be really nice if internal links in readmes worked.

**Comment by eamodio** [comment] 2017-10-02 13:11
@joaomoreno Any update on this? It would be really great if these worked -- I have many links that provide a "link" between a feature and its settings.

See https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens vs https://github.com/eamodio/vscode-gitlens/blob/master/README.md

**Comment by joaomoreno** [comment] 2017-10-03 08:30
@modigrv Any update here?

**Comment by modigrv** [comment] 2017-10-04 12:38
We are investigating and will get back

**Comment by kesane-msft** [comment] 2017-10-06 10:08
@eamodio thanks for bringing this up. We never supported links to other sections in same page on the marketplace site. We have a couple of customers requesting it now and we will put it in our backlog.

**Comment by eamodio** [comment] 2017-10-10 22:41
@kesane-msft thanks. I hope this is something that can be addressed sooner than later. Since GitHub `readme.md` are being pulled into the vscode marketplace directly, I would think (and I certainly do think) that there is a *strong* expectation that something as basic as anchor-linking would be supported.

**Comment by kesane-msft** [comment] 2017-12-21 16:42
@eamodio this is now fixed on the Marketplace.

**Comment by eamodio** [comment] 2017-12-21 18:27
@kesane-msft THIS IS AWESOME -- thank you!

Though I did notice one "issue" while playing with it -- if you click on a link like [eamodio.gitlens#user-content-extension-settings](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#user-content-extension-settings) and then scroll around and click on another link that happens to also go to the same hash it won't re-scroll you to the right position.

**Comment by kesane-msft** [comment] 2017-12-22 04:28
@eamodio thanks for reporting the issue. We'll investigate and get back.

**Closed** 2018-09-20 12:00 UTC
Labels: bug, upstream
