### ISSUE TITLE
Command failed Executing prepublish

### ISSUE THREAD

**Issue by dfinke** [Microsoft/vscode-vsce#104] opened 2016-07-09 18:57 UTC
I published this extension a while ago. https://marketplace.visualstudio.com/items?itemName=DougFinke.vscode-pandoc

I've made some updates and am having this issue packaging and publishing.

Any help is appreciated, thank you.

```
vsce package
Executing prepublish script 'node ./node_modules/vscode/bin/compile'...
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "node ./node_modules/vscode/bin/compile"
```

Here is my package.json
https://github.com/dfinke/vscode-pandoc/blob/master/package.json

**Comment by joaomoreno** [comment] 2016-07-11 07:25
What do you get when running `node ./node_modules/vscode/bin/compile`?

**Comment by dfinke** [comment] 2016-07-11 19:28
Same error. I also removed node_modules and did an npm install

**Comment by joaomoreno** [comment] 2016-07-12 07:23
Any output from `node ./node_modules/vscode/bin/compile` that will lead us to finding out what the problem is?

**Comment by joaomoreno** [comment] 2016-07-21 06:23
Closing as duplicate of #111

**Comment by joaomoreno** [comment] 2016-07-21 06:23
@dfinke Make sure to run `node ./node_modules/vscode/bin/compile` to figure out whether you have any compile errors in your project.

**Closed by joaomoreno** 2016-07-21 06:23 UTC
