### ISSUE TITLE
VSCE does not package node_modules since about October 2 (version 1.81.0)

### ISSUE THREAD

**Issue by mmmyddd** [microsoft/vscode-vsce#497] opened 2020-10-04 12:52 UTC
- Create extension
- Run npm install to create node_modules directory
- Run vsce package in extension directory
- unzip .vsix file
- No node_modules

**Comment by mmmyddd** [comment] 2020-10-04 13:01
I  use npm and not yarn, BTW.

**Comment by felipecrs** [comment] 2020-10-04 17:00
Did you try with `--no-yarn`, so we can check if this issue is the same as #494?

**Comment by mmmyddd** [comment] 2020-10-05 05:21
> Did you try with `--no-yarn`, so we can check if this issue is the same as #494?

Yes, --no-yarn helps, but pls correct this, for npm seems the default option in my point of view

Thank you.

**Comment by laike9m** [comment] 2020-10-05 05:51
This is causing my extension to not function. There's no clear error message when building, which is even worse.

**Comment by Foxhoundn** [comment] 2020-10-05 08:57
Why was this a sudden, silent change like this, from npm to yarn? Everything in our pipelines is failing because none of our images had `yarn` >.<

**Comment by felipecrs** [comment] 2020-10-05 10:18
People, this is a bug being tracked on #494. This is not an intended change.

**Comment by felipecrs** [comment] 2020-10-05 10:21
It should be fixed in newest version, 1.81.1.

**Comment by joaomoreno** [comment] 2020-10-05 13:16
Dupe of #494

Sorry for the breakage yall! Fix is out there!

**Closed by joaomoreno** 2020-10-05 13:16 UTC
