### ISSUE TITLE
hex colors in readme broken

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode-vsce#375] opened 2019-07-17 14:27 UTC
A Readme.md like this: 

```md
## Configure the background:

```json
{
  "myExtension.style": {
    "html": {
      "background": "linear-gradient(45deg, #141414 25%, transparent 25%, transparent 75%, #141414 75%, #141414), linear-gradient(45deg, #141414 25%, transparent 25%, transparent 75%, #141414 75%, #141414)"
    }
  }
}
`` `

```

gets transformed into 

```md 
## Configure the background:

```json
{
  "myExtension.style": {
    "html": {
      "background": "linear-gradient(45deg, [#141414](https://github.com/user/myExtension/issues/141414) 25%, transparent 25%, transparent 75%, [#141414](https://github.com/user/myExtension/issues/141414) 75%, [#141414](https://github.com/user/myExtension/issues/141414)), linear-gradient(45deg, [#141414](https://github.com/user/myExtension/issues/141414) 25%, transparent 25%, transparent 75%, [#141414](https://github.com/user/myExtension/issues/141414) 75%, [#141414](https://github.com/user/myExtension/issues/141414))"
    }
  }
}
`` `
```

I guess this is because of https://github.com/microsoft/vscode-vsce/pull/345

**Comment by oliversalzburg** [comment] 2021-05-07 11:08
IMHO, PR #345 was completely broken and shouldn't have been merged. It doesn't take into account color codes, as reported by this issue, but it also completely ignored code blocks and fixed-width spans.

The cases where this is needlessly broken seem to dramatically outnumber the cases where it has a beneficial effect. I will open a PR to revert this change.

**Comment by joaomoreno** [comment] 2021-11-02 15:44
Duplicate of  https://github.com/microsoft/vscode-vsce/issues/322

**Closed by joaomoreno** 2021-11-02 15:44 UTC
Labels: bug, help wanted
