### ISSUE TITLE
Support symlinks within package

### ISSUE THREAD

**Issue by ArGup** [microsoft/vscode-vsce#308] opened 2018-12-04 13:55 UTC
I am working on an extension which uses a node addon. The node addon in turn has a dependency on a custom mac framework that I am bundling with it. Everything work file in development mode. But when I package the extension using `vsce package`, it removes the symlinks from the Mac framework. Symlinks are required in a mac framework else it does not work. The `.vsix` file, when installed does not load the framework and the extension fails. Is there any option, by which I can instruct `vsce` not to remove symlinks. 

1. I have tried not to bundle the framework with extension and added the framework as a dependency(in package.json). But `vsce` brings all the dependencies while packaging. Ideally the dependencies should come at runtime i.e. when VSCode is installing the extension. 

2. I then tried to unpackage the `.vsix` file and then replaced the framework with my original framework and then repackaged it into `.vsix`. But when VSCode installs `.vsix`, it again removes the symlinks from framework, thereby corrupting it.

Please guide. Thanks.

**Comment by joaomoreno** [comment] 2018-12-06 07:51
> Now if you bundle this framework in your extension and use vsce package command, it will completely remove the Resources symlink and and it will replace that CoreFoundation symlink with actual binary at ./Versions/A/CoreFoundation. This way it corrupts the structure of Mac framework and it fails to load.

May I ask why you are including a macOS framework within your extension?

**Comment by ArGup** [comment] 2018-12-06 08:17
I have created a custom mac framework which contains my business logic. Basically i am working on debug adapter. The APIs are exposed through that mac framework. And yes i can make that a dylib but the problem is it has more dependence on other frameworks. What i want to ask is, is there any option by which i can instruct `vsce` not to touch symlinks. If there is not, then can I ask for dependencies at install time i.e. can vscode do `yarn install` in my extension package after it has done installation?

**Comment by joaomoreno** [comment] 2018-12-06 08:34
There's no good suggestion I can give you right now. Needs fixing to support symlinks. Sorry about that!

**Comment by ArGup** [comment] 2018-12-06 08:45
No problem. Will look for workaround for the time being. Thanks anyways :)

**Comment by cagdas001** [comment] 2018-12-21 20:48
I'm also having this. I'm spawning external *Electron* apps for some features in the extension. The *Electron* binary  location on **macOS** (no problem on *Window*s with *EXE* file) is `node_modules/electron/dist/Electron.app/Contents/MacOS/Electron` It works properly when debugging in dev environment. But when I package the extension into VSIX, `vsce` removes some symlinks from `Electron.app` Therefore `node_modules/electron/dist/Electron.app/Contents/MacOS/Electron` executable cannot find a library and gets crashed.

I think we can add an option that allows user to enable this feature (e.g. called `--include-symlinks`, or something like that) 

So 

```sh
vsce package
```
will work as it currently is.

If user needs this feature,

```sh
vsce package --include-symlinks
```
will do the job.

What's your thoughts? I guess I'll be able to open a PR for this

**Comment by cagdas001** [comment] 2018-12-22 09:36
@ArGup thanks, I'll temporarily use a similar solution to yours

If VSCode also ignores symlinks within package (have not investigated yet, how it does this), maybe we can add a flag in the package manifest.

If `vsce package` command called with `--include-symlinks` then VSCode will know this from the flag and will not ignore symlinks

I think this optional way is better rather tah getting all symlinks in all cases

**Comment by phgn0** [comment] 2019-11-10 16:16
I can confirm `vsce package` ignores symlinks currently.

I temporarily fixed it for my usecase by manually resolving the symlink (i.e. duplicating the files).

**Comment by panoply** [comment] 2020-04-29 01:57
I use [pnpm](https://pnpm.js.org/) which symlinks modules. Vsce being unable to support symlinks means preserving dependencies within `node_modules` like the vscode-languageserver is not possible. Would be cool to see this supported.

**Comment by sguillia** [comment] 2020-11-30 13:15
Hi!

Dead simple [npm links](https://docs.npmjs.com/cli/v6/commands/npm-link) are also not supported

**Comment by KevinEady** [comment] 2021-03-21 19:49
Hello,

Is there any progress on this? My use-case is a little different (not embedding Mac Frameworks), but I do want to have symlinks across modules in my extension.

I am creating an LSP extension, and my extension structure is as such:
```
extension
├── client
├── native
└── server
```

... where `server` has a dependency on `native`, via `file:../native`

My extension comes with native Node bindings, so I cannot webpack them into one JavaScript source. The LSP part works between `client` and `server`, because it does not `require()` the server by module name but by absolute path, see https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/client/src/extension.ts#L20 . I could move my native bindings into the `server` module, but I prefer to keep it self-contained for separation of concerns.

My workaround was something similar:
```ts
// Does not work, as `native` does not exist. In my dev workspace where
// I perform `vsce package`, it is a symlink to `server/node_modules`
import { foo } from 'native';

// Workaround
const { foo } = require('../../../native') as typeof import('native');
```

Workaround works, but I just wanted to provide additional use-cases for this feature.

Thanks, Kevin

**Comment by ganeshrn** [comment] 2022-04-14 07:51
> Is there any way to raise awareness about this issue? In a world where many extensions are using language-servers, which are separated projects, they also need to test with main branch of their language-servers, so they need to build an extension using a linked npm package.

Agreed, to test unreleased versions for cross project testing  it requires hack like these https://github.com/ansible/ansible-language-server/blob/v0.6.1/.github/workflows/vscode.yml#L37 which results in other problems.

**Comment by ssbarnea** [comment] 2022-06-17 08:59
As the main issue with this is related with `npm link` which continues to be broken even after years, it worth mentioning that `yarn link` support is in much better shape.

That made us start a switch from npm to yarn for our extension and once #743 is sorted we will be able to finish the switch.

**Comment by benibenj** [comment] 2024-12-11 09:04
The `package`, `ls` and `publish` commands support `--follow-symlinks` to get files from symlinks when collecting files to publish

**Closed by benibenj** 2024-12-11 09:04 UTC
Labels: help wanted, feature-request
