### ISSUE TITLE
Auto-Generated Tags by VSCE

### ISSUE THREAD

**Issue by anupkmr03** [microsoft/vscode-vsce#820] opened 2023-01-30 10:43 UTC
While publishing VS Code extension on the marketplace, there is a validation that limits the number of tags to 10 (configurable), excluding the hidden ones that start with "__*".

However, it seems that there are many different types of tags being auto-generated by VSCE, which is causing many publishers to be unable to publish their extension.
Do we have a fixed set of identifiers to identify the auto-generated tags, so that the marketplace can ignore these tags in this validation?

Additionally, I noticed that there are many VS Code extensions that have a large number of auto-generated tags, with some even exceeding 500 or 1000. Are these numbers expected, or is there a bug causing this?

As examples, here are a few Vs code extensions where the auto-generated tags are particularly large:
 https://marketplace.visualstudio.com/items?itemName=phileagleson.poweron-vscode [Around 1000+ tags]
 https://marketplace.visualstudio.com/items?itemName=vakaras.vscode-language-pack-lt
 https://marketplace.visualstudio.com/items?itemName=curlybracket.vlocode

**Comment by joaomoreno** [comment] 2023-01-31 11:12
Duplicate of microsoft/vsmarketplace#569.

**Closed by joaomoreno** 2023-01-31 11:12 UTC
